version: '3.8'

services:
  # The Relational Database for Audit Logging
  postgres:
    image: postgres:15-alpine
    container_name: fraud_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fraud_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # The In-Memory Cache for Rate Limiting / High-Speed State
  redis:
    image: redis:7-alpine
    container_name: fraud_redis
    ports:
      - "6379:6379"

volumes:
  pgdata: