from pydantic import BaseModel, Field, ConfigDict
from datetime import datetime, timezone

class TransactionRequest(BaseModel):
    """
    Strict validation schema for incoming transaction payloads.
    Enforces data types and mathematical boundaries to prevent model corruption.
    """
    transaction_id: str = Field(
        ..., 
        min_length=10, 
        max_length=50, 
        description="Unique identifier for the transaction"
    )
    user_id: str = Field(
        ..., 
        min_length=5, 
        max_length=50, 
        description="Unique identifier for the user making the request"
    )
    amount: float = Field(
        ..., 
        gt=0.0, 
        le=1_000_000.0, 
        description="Transaction amount in USD. Must be strictly positive."
    )
    velocity_1h: int = Field(
        ..., 
        ge=0, 
        le=10_000, 
        description="Number of transactions by this user in the last hour."
    )
    device_risk_score: float = Field(
        ..., 
        ge=0.0, 
        le=1.0, 
        description="Browser/device fingerprinting score generated by the frontend."
    )
    
    # We enforce timezone-aware datetimes
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc), 
        description="UTC timestamp of the transaction request"
    )

    # Enterprise Configurations
    model_config = ConfigDict(
        str_strip_whitespace=True,  # Security: Prevent whitespace padding attacks
        frozen=True,                # Thread-safety: Make instances immutable
        json_schema_extra={
            "example": {
                "transaction_id": "tx_9876543210abcd",
                "user_id": "usr_12345",
                "amount": 150.75,
                "velocity_1h": 3,
                "device_risk_score": 0.15,
                "timestamp": "2023-10-27T10:00:00Z"
            }
        }
    )

class TransactionResponse(BaseModel):
    """
    Data contract for the API response. 
    Guarantees the frontend receives a predictable shape.
    """
    transaction_id: str = Field(..., description="Echoed transaction ID for tracing")
    risk_score: float = Field(..., ge=0.0, le=1.0, description="Raw ML probability of fraud")
    action: str = Field(
        ..., 
        pattern="^(APPROVE|REVIEW|BLOCK)$", 
        description="Deterministic action based on risk thresholds"
    )
    latency_ms: float = Field(..., description="Total processing time in milliseconds")
    
    model_config = ConfigDict(frozen=True)